# Generated by Django 2.2.16 on 2020-10-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_app', '0003_auto_20201018_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='emp_id',
            field=models.CharField(default='ABC', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='CINA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='activity_periods',
            field=models.ManyToManyField(blank=True, to='initial_app.ActivityPeriods'),
        ),
    ]
